packages:
  - 'server'
  - 'client'
allowBuilds:
  bcrypt: set this to true or false
  esbuild: set this to true or false
  node-pty: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies: '["bcrypt", "esbuild", "node-pty", "sharp", "unrs-resolver"]'
